SELECT DISTINCT city FROM employeeTerritories et; 
SELECT employee_no, last_name FROM employees e ORDER BY last_name ASC; 
SELECT ROUND(AVG(salary),0) FROM salaries;
SELECT COUNT(gender) AS Female FROM employees e;
SELECT employee_no, first_name, last_name, hire_date FROM employees ORDER BY hire_date DESC;
SELECT first_name, last_name, birth_date FROM employees WHERE birth_date >= "1960%";
SELECT employee_no, title FROM titles WHERE title IN ("Tehnique Leader", "Senior Engineer");
SELECT employee_no, city FROM employeeTerritories et WHERE city != "Kyiv";
SELECT first_name, last_name, birth_date FROM employees WHERE first_name LIKE "Ma%";
SELECT last_name, birth_date FROM employees WHERE birth_date BETWEEN "1960-01-01" AND "1964-12-31";
SELECT employee_no, city FROM employeeTerritories et2 WHERE city LIKE "K%" and LENGTH(city) >= 4;
SELECT employee_no, city FROM employeeTerritories et WHERE city IN("Dnipro", "Kyiv", "Lviv");
SELECT COUNT(title) AS "total engineers" FROM titles t WHERE title = "Engineer";
SELECT COUNT(employee_no) AS Employees, city FROM employeeTerritories et GROUP BY city HAVING COUNT(employee_no) > 10;
SELECT first_name, last_name, title FROM employees e JOIN titles t ON e.employee_no = t.employee_no; 
SELECT first_name, last_name, salary FROM employees e JOIN salaries s ON e.employee_no = s.employee_no WHERE salary BETWEEN 50000 AND 60000;
INSERT INTO employees (employee_no, birth_date, first_name, last_name, gender, hire_date) VALUES ("10101", "1995-11-30", "Emily", "Jenkins", "F", "2000-02-02");
DELETE FROM employees WHERE employee_no = "10101";
SELECT title, COUNT(employee_no) FROM titles GROUP BY title HAVING COUNT(employee_no) > 150;
